added all functionalities
balgyn98/bookstore pull request #1
Opened 2024-11-04 20:31 UTC by balgyn98

Bookstore simple java application

2024-11-05 15:30 UTC, Alexmansar requested changes
@balgyn98 Hi)) In general good job, but I have some comments) so, please just fix it and send me again)

2024-11-05 15:30 UTC, Alexmansar commented on src/Book.java
> +    // fields
That's an unnecessary comment.

2024-11-05 15:30 UTC, Alexmansar commented on src/Book.java
> +    // constructor
same

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +                    break;
use new switch style with ->

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +                // get all orders
overall complex logic.
Please try to optimize it, at least create simple methods to make it easier to read.

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +        Scanner sc = new Scanner(System.in);
scanner (full name, more easy to read)

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +        library.addBook(book5);
just to improve memory usage 
library.addBook(new Book(1, "Harry Potter", "J.Rowling", date, 1300));
i mean without creating variables, you we don't use it again)

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +            sc.next();
not need here. you already in catch block

2024-11-05 15:30 UTC, Alexmansar commented on src/Main.java
> +        return duration.toMinutes() < 2;
what is 2? could you add please some name, or use like a constant?

2024-11-05 15:30 UTC, Alexmansar commented on src/Order.java
> +    private int ID;
small style
just id;

2024-11-06 07:55 UTC, Alexmansar requested changes
@balgyn98 I have new general comments) please, check it

2024-11-06 07:55 UTC, Alexmansar commented on src/Main.java
> +    }
you can create CustomerService and more logic

2024-11-06 07:55 UTC, Alexmansar commented on src/Main.java
> +    public static boolean createUser(Scanner scanner){
same for User

2024-11-06 07:55 UTC, Alexmansar commented on src/Main.java
> +    public static void createOrder( Customer user, Scanner scanner){
and for rorder

In general, move such methods to the specific classes))

2024-11-06 10:45 UTC, Alexmansar commented on src/service/OrderService.java
> +    public static void createOrder(Customer user, Scanner scanner, Library library, BookStore store){
same

2024-11-06 11:36 UTC, Alexmansar approved these changes
@balgyn98 
Hi again))) good job in general)
please, fix last comment and merge it))

2024-11-06 11:36 UTC, Alexmansar commented on src/Main.java
>  }
and now, I think we can move it to the Library))

2024-11-06 11:38 UTC, balgyn98 commented on src/Main.java
>  }
thank you so much!) learnt many things from this task

2024-11-06 13:14 UTC, merged